ARG OCAML_VERSION=4.9.1
FROM reasonnative/ocaml:$OCAML_VERSION

LABEL maintainer "Ulrik Strid <ulrik.strid@outlook.com>"

ARG OCAML_VERSION=4.9.1

ENV TERM=dumb LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib

RUN echo ' \
    {\
    "name": "package-base", \
    "dependencies": { \
    "ocaml": "~'"$OCAML_VERSION"'", \
    "@opam/dune": ">= 2.0.0", \
    "@reason-native-web/morph": "^0.4.0" \
    } \
    } \
    ' > esy.json

RUN esy install

RUN esy build --release
