# syntax = docker/dockerfile:experimental
FROM node:12

RUN npm install -g esy

LABEL maintainer "Ulrik Strid <ulrik.strid@outlook.com>"

ARG OCAML_VERSION=4.9.1

ENV TERM=dumb LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib

RUN mkdir /tmp/app
WORKDIR /tmp/app

RUN echo ' \
    {\
    "name": "package-base", \
    "dependencies": { \
    "ocaml": "~'"$OCAML_VERSION"'" \
    } \
    } \
    ' > esy.json

RUN cat esy.json

Run echo boo

RUN --mount=type=cache,target=/root/.esy/ esy

RUN echo foo


