name: Build and Publish to Docker Hub
on: [push]

env:
  DOCKER_BUILDKIT: 1
jobs:
  build-and-deploy-esy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v2
      - uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" \
            --file ./Dockerfile.ocaml \
