name: Build and Publish to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ESY_VERSION: ['0.6.2']
        OCAML_VERSION: ['4.7.1', '4.8.1', '4.9.0']  
    steps:
      - uses: actions/checkout@v2
      
      - name: Build esy image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          ./build-and-push.sh ${{ matrix.ESY_VERSION }} ${{ matrix.OCAML_VERSION }}
          docker logout
