name: Build and Publish to Docker Hub
on: [push]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-deploy-esy:
    runs-on: ubuntu-latest
    steps:
      - name: Cache docker
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/docker_cache
          key: test-6
      - uses: actions/checkout@v2
      - name: Restore docker
        run: ./.github/actions/docker-cache/restore.sh ${{ runner.temp }}/docker_cache/cache.tar
      - name: Build esy image
        run: |
          docker build --rm -f "Dockerfile.ocaml" "."
      - name: Backup docker
        run: ./.github/actions/docker-cache/backup.sh ${{ runner.temp }}/docker_cache/cache.tar
