name: Build and Publish to Docker Hub
on: [push]

jobs:
  build-and-deploy-esy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ESY_VERSION: ['0.6.2', '0.6.4']
    steps:
      - name: Stupid
        run: |
          sudo chown -R $(whoami):$(id -ng) /var/lib/docker
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker
          key: ${{ runner.os }}-test3
      - uses: actions/checkout@v2
      
      - name: Build esy image
        run: |
          DOCKER_BUILDKIT=1 docker build --rm -f "Dockerfile.esy" --build-arg ESY_VERSION=${{ matrix.ESY_VERSION }} -t reasonnative/esy:${{ matrix.ESY_VERSION }} "."
      - name: Stupid 2
        run: |
          sudo chown -R $(whoami):$(id -ng) /var/lib/docker
